### ISSUE TITLE
Feature: Form-wide validation messages

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#115]
## What
Need to have an ability to handle form-wide validation messages.

## Why
Imagine a failure response from the `Form.props.action`. There should be a way to handle it in the UI with ease.

**Comment by kettanaito** [comment]
Makes me thinking of something like `Form.Message`.

The component should not be bound to errors only. In the future we should handle success messages as well (mb even warning messages). `Form.Message` can act straightforward - listen to the form submit resolve status and provide it as a prop for the end developer to create the logic.

However, this will force `Form.Message` to always be rendered within the `Form` component, which is not very flexible. Ideally, the end developer should be able to place some form-wide message anywhere in the layout.

### Draft
```jsx
<Form>
  <Form.Message handle={({ response, fields, form }) => { ... }}>
    <p>Form submit failed.</p>
  </Form.Message>
</Form>
```

**Comment by Vidlec** [comment]
Is that needed? We can provide message on submitSuccess/Failed callback this looks enough...
Maybe we can provide both. If you want message inside form use Form.Message if you want it anywhere else get it from callback...

**Comment by kettanaito** [comment]
@Vidlec so, delegate the responsibility of form-wide validation message to the end developer entirely?

I believe the response of the `action` is available in both `onSubmitFailed` and `onSubmitted`, so you can handle different validation messages on your own.

Think of Conrad use cases, we still have a form-wide validation messages, and it would be nice to have them unified somehow.

**Comment by kettanaito** [comment]
So, one of the possible ways to handle this is to do something like:
```jsx
export default class MyForm extends React.Component {
  state = {
    errorMessage: null
  }

  handleSubmitFailed = ({ res }) => {
    const { errorCode } = res.body;
    const errorMessage = messages[errorCode];
    
    if (errorMessage) this.setState({ errorMessage });
  }

  render() {
    const { errorMessage } = this.state;

    return (
      <div>
        <Form onSubmitFailed={ this.handleSubmitFailed } />
        { errorMessage && (<SomeMessageComponent>{ errorMessage }</SomeMessageComponent>) }
      </div>
    );
  }
}
```

### Pros
* Complete freedom of the logic handled by the end developer
* Ability to display the message anywhere; message display logic is not connected to the Form logic at all
* Reusing the existing functionality

### Cons
* Maybe too much boilerplate given to the end developer?
* Form handles nothing regarding form-related message, which is somewhat strange

**Comment by kettanaito** [comment]
The outcome is:
1. Form-wide error messages are often based on the action's response, yet the logic of that is very diverge. There is no need to predict how the end user's error message logic should work.
1. Current implementation provides everything to have form-wide validation messages without any hiss.

Closing.
