### ISSUE TITLE
Form: Make "rules" and "messages" optional props

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#120]
## What
Need to make the mentioned props optional.

## Why
It's confusing to get errors when trying out the form. Moreover, there should be nothing bad to allow to use the form without any rules or messages.

**Comment by kettanaito** [comment]
Now you don't need to provide any `rules` nor `messages` to the `Form` component in order for it to work properly. Closing.

@jonasdumas.

**Comment by jonasdumas** [comment]
Excellent !
