### ISSUE TITLE
Library of predefined rules that cover standard needs

### ISSUE THREAD

**Issue by jonasdumas** [kettanaito/react-advanced-form#124]
I'm wondering if you already have a library with a set of standard rules (email, text field size min/max, date range, etc) ?
It would be helpful to have such resources such as 99% of validation rules are basic and universal... no need to reinvent it on each project.

**Comment by kettanaito** [comment]
Hi, @jonasdumas.

This sounds interesting, but I cannot think of any universal validation rules except of email. And even the email may be valdated differently: the one may use some validation library as a dependency, the other may be fine with a simple RegExp.

The versatility of the current validation declaration approach is that it's just a map of pure functions. Enforcing certain behaviors or dependencies doesn't seem right here. Also, this idea can be related to `type` validation only, which is only a half of validation fuctionality. This would mean the necessity of extending this validation schema almost each time.

Things like field length or min/max is also easily configurable manually:
```js
someField: ({ value }) => value.length > 7
```

I think in reality most projects indeed need their own custom validation rules, there is nothing bad about this. But let me know how you see it, maybe in more details/examples. Thanks.

**Comment by kettanaito** [comment]
If you wonder on my personal preferences, I tend to use `validator` library, specifically `isEmail` function. All the other rules are achieved by RegExp.

**Comment by jonasdumas** [comment]
Thanks for you answer and for your suggestion about validator.
I understand your remarks that make sens for me.
I'll implementing RAF validation form solution and go thru all my forms the first week of january. I need that to have a more clear idea about the topic. Then, I might come back to you with a more opinionated answer if I'll get any.
