### ISSUE TITLE
Passing undefined as an initialValue causes unhandled error in form.updateField

### ISSUE THREAD

**Issue by Vidlec** [kettanaito/react-advanced-form#133]
In this case fieldProps.merge throws, because fieldProps is undefined

**Comment by jonasdumas** [comment]
I got same error with Null value in intialValue.
I had to check value and correct it on each field if null.
Would be nice to be able to pass any type of value

**Comment by kettanaito** [comment]
Could you please include the stack trace and component's declaration? Thanks.

**Comment by Vidlec** [comment]
Please check PR #134

**Comment by kettanaito** [comment]
@Vidlec your pull request is good, but I would like to know more info on the issue. Sometimes a proper fix is not where you would initially expect it to be.

Please see the comments in the pull request and thanks for spotting the issue!

**Comment by jonasdumas** [comment]
I'm not sure if it's the same bug, but when a field is set with an initialValue of Null or Undefined it throw an error:
`Uncaught TypeError: Cannot read property 'merge' of undefined`

**Comment by Vidlec** [comment]
Yes, it's the same bug. I am currently investigating further. It seems
there is an issue with field life cycle methods.

**Comment by Vidlec** [comment]
Found the issue.

problem is `const registeredValue = isset(contextValue) ? contextValue : (value || initialValue || '');`
in `Field.registerWith`

The thing is - if we pass undefined to Input, its saved as an '' into context.
But later in `componentWillRecieveProps` of `Field` we call `getPropsPatch` with the original props. So it thinks we changed something and calls fieldUpdate on Field which is not yet registered. 

Removing ` || ''` fixes the issue and works well. I dont know why it is even there.
@kettanaito ?

**Comment by kettanaito** [comment]
@Vidlec, thanks for the details.

Having "" is necessary as a fallback value, but we need to check it thoroughly.

However, there is no way receiveProps is called with unregistered field. I need to take a look into that.

**Comment by kettanaito** [comment]
@jonasdumas , @Vidlec , I am investigating this issue and cannot reproduce it.

Please, could you help me out by seeing `bugfix/field-initial-value` branch?
It's based on the latest master, and it has a `Field.spec.js` which contains this `initialValue` bug scenario. However, the scenario resolves, I only receive a "controlled/uncontrolled" React's error, which is completely expected when having `<input initialValue={ undefined } />`.

Thanks.

**Comment by kettanaito** [comment]
Found a reason for this issue. On it.

**Comment by kettanaito** [comment]
## Reason
This issue was related due to the `initialValue` fallback value upon field's registration:
```jsx
const foo = (value || initialValue || '');
```

By registering the field with `initialValue: ''` the props patch comparison failed because the original props of the field still have `initialValue: undefined`. This resulted into `initialValue` being treated as a prop patch to update, that triggered `updateField()` and resulted into mentioned error.

**Comment by kettanaito** [comment]
This issue is fixed in `0.15.4` release.
