### ISSUE TITLE
Rendering fields - having a native RAF function ?

### ISSUE THREAD

**Issue by jonasdumas** [kettanaito/react-advanced-form#135]
For my project needs, I've created a basic "renderField" class to display errors/valid messages and classnames on all fields.

It would be nice to have a native default RAF class to do it such as it's common to every project. Something like
`import {renderField} from "react-advanced-form"`

It would be more fast to implement RAF for any new developper. And it would be still possible to not use it if one prefer a custom rendering component as it's now.

Below the basic class I've done. I've used the example provided by RAF as a base. It's using css classname instead of programmatic styles. I'm not saying it's a better approach but it's the one i choose for my project.

Also, there's a Switch(type) to find the right field to render. Maybe, it may have a better approach that consume less ressources. It's fine for a personal class as it's possible to complete the list with all personals customs fields. But for a "native" class, it would need options to extends the renderField with customs fields.

```jsx

import { Field, connectField } from 'react-advanced-form';
import feather from 'feather-icons';
import FieldSelect from **CUSTOM FIELD PATH**;
import FieldDropzone from  **CUSTOM FIELD PATH**;

class RenderField extends React.Component {

    static defaultProps = {
        fieldType : 'Input',
    }

    renderField = (type) => {

        switch (type) {
            case "Input" :
                return <Field.Input {...props} />
            case "Textarea" :
                return <Field.Textarea {...props} />
            case "Checkbox" :
                return <Field.Checkbox {...props} />
           /* custom fields */
            case "Select" :
                return <FieldSelect {...props} />
            case "Dropzone" :
                return <FieldDropzone {...props} />
            
        }

    }

  render() {
    const { valid, invalid, error, validating, disabled, fieldType, label } = this.props;
    const iconOptions = { width: 20, height: 20 };
    const className = (valid && 'valid') || (invalid && 'error');
    const icon = (valid && feather.icons.check.toSvg(iconOptions)) || (invalid && feather.icons['alert-circle'].toSvg(iconOptions));
    const opacity = disabled ? '0.5' : 1;

    return (
      <div className={`form-field ${className}`} style={{ opacity  }}>
          <label>
              {label}
              { this.renderField (fieldType) }
          </label>
          { (valid || invalid) && (
            <span
              className="icon"
              dangerouslySetInnerHTML={{
                __html: icon
              }} />
          ) }

        { validating && <p>Validating...</p> }

        { invalid && (
          <span className="message">{ error }</span>
        ) }
      </div>
    );
  }
}
export default connectField(RenderField);
```

**Comment by Vidlec** [comment]
@kettanaito Maybe let's create different package for this? Like `react` and `react-dom` do.
I don't want to increase size of this package much further :)

`react-advanced-form-templates` or similar.

**Comment by kettanaito** [comment]
While this may suit certain needs, I find this too specific to include in the library.

There is no way and need to assume the layout of custom fields, and everything else is already covered by `connectField`. The less things are enforced - the more reusable and flexible is the solution. Feel free to create new project for this, or we can refine existing solution to add the things you find missing there.

**Comment by kettanaito** [comment]
Sorry, don't find the logic in this request dynamic enough to be put into a separate library.

Feel free to put this logic into your public/private package to reuse between your projects. Closing.
