### ISSUE TITLE
Separate native fields into a dedicated package

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#144]
## What
I think we need to separate the native fields (`Field.Input`, `Field.Select`, etc.) into a dedicated package.

## Why
Shipping ~5 Kb of native fields into production projects which have their own custom fields is a huge size overkill.

## How
1. Create a new repo `react-advanced-form-addons`.
1. Move the fields' implementation there.
1. Publish to NPM.

@Vidlec, @jonasdumas, This is something similar to what you have suggested previously, so I wanted to let you know.

**Comment by Vidlec** [comment]
hmmmm 🤔 
should there be several "themes"?
How to organise this?

`react-advanced-form-theme-material`
`react-advanced-form-addon-superCoolSelector`

**Comment by Vidlec** [comment]
Now when we switched to preset... 
`react-advanced-form-addon-presets`
or
`react-advanced-form-presets`

**Comment by kettanaito** [comment]
@Vidlec, as discussed regarding presets - there are currently only 3 presents needed for native fields. Other basic form elements use just `createField()` plainly. I do not see the reason to move those 3 Objects into a dedicated packaged. For your custom fields you would write you own options for `createField()` anyway.

Regarding the theme - I am not sure what to say on this topic. What I definitely would like to do is to keep the package names short, as they are quire long on their own.

We can always design a neutral UI theme which will look okay on any surrounding UI theme. `-addons` are meant for fast prototyping, **not for production usage**. You still need to style your fields by yourself for production.

**Comment by kettanaito** [comment]
@Vidlec, I would appreciate your thoughts on the appearance of `react-advanced-form-addons` by default. Feel free to share some designs you like and find neutral enough. Thanks!

**Comment by kettanaito** [comment]
## Update
A collection of styled fields has been published under the dedicated [`react-advanced-form-addons`](https://github.com/kettanaito/react-advanced-form-addons) repository and package. We may want to consider something like Lerna in the future.

Closing.

**Comment by jonasdumas** [comment]
I'll study that next few weeks. Thanks for all improvments

**Comment by kettanaito** [comment]
@jonasdumas Thank you for staying in tune.

I'm sorry for no migration guides, since the implementation is rapidly improving and changing it makes it hard to write some defined guides before the 1.0 release, where the API will be stable.

I hope by that time I will finish with basics of `react-advanced-form-addons` that are now in active development, so you could give it a try :)

**Comment by jonasdumas** [comment]
Np, no need to have a migration guide at this step of the project. 
Looking forward to see how react-advanced-form and addons works together !

**Comment by jonasdumas** [comment]
If it can help, here's a simple example of design for the form.
<img width="978" alt="react-advanced-form" src="https://user-images.githubusercontent.com/14850054/35391660-956b7082-01df-11e8-8b73-1c379c69ee09.png">

**Comment by kettanaito** [comment]
@jonasdumas thank you! We will be using something very similar. Stay tuned, I will post an update in `react-advanced-form-addons` repository!
