### ISSUE TITLE
Allow "Field" to be controlled by the end developer

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#20]
## What
Need to think of a proper way how to allow the end developer make certain properties on `Field` controlled.

## Why
You expected
```jsx
<Field.Input value="My value" disabled={ isLoading } />
```
to work directly.

## How
1. Let's agree that the `Field` is always controlled by the `context`. We need to pick a single source of truth, and internal context updating mechanism is more reliable than custom props passed in.
2. Handle the updates of custom controlled props through `componentWillRecieveProps` to remap them in the `context` as well?

**Comment by kettanaito** [comment]
## Update
Direct props passed to `<input>` (i.e. `type`) are updating properly already.

The issue lies with the Field-specific props (i.e. `rule`, `asyncRule`). Those are changing in Field.props.

**Comment by Vidlec** [comment]
Is this still relevant?

**Comment by kettanaito** [comment]
@Vidlec well, some properties (i.e. `value`, ... is that all?) are working as controlled just fine. However, another (i.e. **`disabled`**, `rule`, `asyncRule`) seem not to work properly.

Can we setup some story in storybook to test all the props we need as controlled?

**Comment by kettanaito** [comment]
This request will be covered under #38. No need to duplicate. Closing.
