### ISSUE TITLE
Ensure "asyncRule" function can have custom Promise resolver

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#22]
## What
Need to ensure that `asyncRule` function can have custom Promise resolver.

## Why
It's most likely developers would have their own resolve logic based on the WS response. It doesn't necessarily means that the request should resolve. It may have additional logic (i.e. depend on `statusCode`)

## How
This is one of the expected usages of `asyncRule`:
```jsx
<MyField asyncRule={() => fetch('https://backend.dev/ws', { ... }).then((payload) => {
  return (payload.statusCode !== 'ERROR')
}) } />
```
This reads: the field is considered valid unless `payload.statusCode` equals `ERROR`. In case the request throws, this should be handled automatically as invalid state of the field.

**Comment by Vidlec** [comment]
Also how to provide error message? As you can get message from WS or some error code...

**Comment by kettanaito** [comment]
@Vidlec yeap, need an easy way to bind async validations and their error messages.

**Comment by kettanaito** [comment]
@Vidlec the error messages for async validation have been provided within #25.

You can now handle async validation through `FormProvider` or directly in `Form`:
```jsx
<FormProvider messages={{
  name: {
    email: {
      invalid: 'Please provide a proper email.', // sync validation
      async: { // async validation
        userExists: ({ payload, fieldProps }) => {
          if (payload.errorCode === '1234') {
            return `User with the email "${ fieldProps.value }" already exists."
          }
        }
      }
    }
  }
}}>
</FormProvider>
```
Each validation resolver has its unique key (`userExists` in the example above) for the sake of passing this key down to the custom UI component in the future. Maybe designers would want to show different UI behaviors depending on the validation outcome. This way we achieve granular control.

**Comment by kettanaito** [comment]
## Update
`Field.props.asyncRule` is now expected to return an Object of a following shape:
```js
{
  valid: boolean,
  ...rest
}
```
The validity of the field will be set based on the provided `valid` property. In case the field is invalid, all `...rest` properties passed from the `asyncRule` prop will be available in the error message resolver:
```jsx
const errorMessages = {
  name: {
    username: {
      async: {
        userExists: ({ value, errorCode }) => {
          return `User with the name "${value}" already exists. ${erroCode}.`;
        }
      }
    }
  }
};
```

<Field.Input
  name="username"
  asyncRule={({ value }) => fetch(...).then(res => res.json()).then((payload) => {
    return {
      valid: payload.statusCode === 'SUCCESS',
      errorCode: payload.errorCode
    };
  }}
  required />
```
Closing.
