### ISSUE TITLE
Consider adding "aria-" attributes

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#247]
## Environment
* **react-advanaced-form:** 1.3.0

## What
I suggest to consider adding `aria-` attributes.

## Why
Accessibility.

## How
1. Read about the current approach to `aria-` attributes.
1. Add the tags, if found necessary.

**Comment by kettanaito** [comment]
Most of the `aria-` attributes reside on the field component directly, which implementation, including the layout, is completely open to the end developer. This task may involve to read which things can be set on the Form itself, since that is the only component which layout is hard-coded from the library side.

**Comment by kettanaito** [comment]
Having read through multiple ARIA-related articles, I haven't found anything which is designed to be put into `<form>` element directly. All form ARIA attributes are rather put into fields, which are in full control of the end developer.

What makes sense to do is to add ARIA attributes to `react-advanced-form-addons` library, to have up-to-standards fields.

**Comment by Vidlec** [comment]
I think form element is semantic enough on its own, so it doesn't need anything :)

**Comment by kettanaito** [comment]
@Vidlec Yes, I agree. There isn't much to set on the form component in terms of accessibility. That, however, can (and I think should) be done on fields. Since those aren't the part of the repository yet, I think this issue is not relevant at the moment. Thanks for the input.
