### ISSUE TITLE
Feature: Form.props.onChange

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#254]
## What
Maybe there is a use case to have a general `onChange` handler assigned to the `Form`, which fires each time any field inside changes.

`onChange` handler is different from `onDirty` because `onChange` fires *each* time any field is changed within the form, while `onDirty` fires only *once*, when the first change happens.

### Definition
```ts
type onChange = ({ prevValue, nextValue, fieldProps, fields, state }) => void
```

### Usage example
```jsx
class ExampleForm extends React.Component {
  handleFormChange = ({ prevValue, nextValue, fieldProps, fields, form }) => {
    console.log(
      'Field `%s` changed from `%s` to `%s`,
      fieldProps.name, prevValue, nextValue
    )
  }

  render() {
    return (
      <Form onChange={this.handleFormChange}>
        {/* Fields */}
      </Form>
    )
  }
}
```

## How
Need to proof this feature is really useful and has a reason.

- [ ] Add a new `onChange` prop for the `Form` component. Include PropTypes annotation.
- [ ] Dispatch `Form.props.onChange`, whenever present, after the logic within `Form.handleFieldChange`. Align its interface according to the specification.
- [ ] Create an integration for the feature.

**Comment by Vidlec** [comment]
What would be the handler value? Props of changed field? I tried, but I cant think of a single reasonable use case...

**Comment by kettanaito** [comment]
@Vidlec I think the interface can be like follows:

```js
onChange = ({ nextValue, prevValue, fieldProps, fields, form }) => {}
```

So, it's completely the same as `Field.onChange` handler/callback.

The use cases for this feature may be as follows:
1. Developer wants to keep the form values in some sort of state (i.e. Redux store). Instead of hooking each `onChange` handler individually, it can hook once into `Form.onChange` handler.
1. Developer wants to flush the values of the fields into localStorage, or any other storage, upon any change. Again, just a shortcut which ensures no matter what fields are in the form, their change will always trigger `Form.onChange` handler.

There were another cases, but I can't recall them right now. I will update them here if I remember.
That's a good catch, thanks. We do need to prove its useful/useless.

**Comment by kettanaito** [comment]
Since this is a rather minor change to the code base, I have moved it to `1.x` milestone.

**Comment by kettanaito** [comment]
After giving this proposal another thought, I think it would be a good example of over-engineering.

* Having explicit `onChange` on field components is clear and easily maintainable
* There is no scenarios that explicit `onChange` handlers on fields cannot handle

Closing this.
