### ISSUE TITLE
Parameters for rules and messages for reuse

### ISSUE THREAD

**Issue by T-Roth** [kettanaito/react-advanced-form#259]
Is there a way to provide parameters to the rules and messages so something like minLength could be reused with a different size params?   I would really like to not have 100 different minLengthXXX rules in my app.

**Comment by kettanaito** [comment]
I'm not sure what you mean.

I would encourage you to write validator functions as pure high-order functions. What I mean by that:

```js
// validators/minLength.js
export default function minLength(length) {
  // returns a validator function expected by RAF
  return ({ value }) => {
    return value.length >= length
  }
}
```

Then you can use this function anywhere, if necessary:

```js
import minLength from './validators/minLength'

const rules = {
  firstName: {
    yourRuleName: minLength(6) // reads "must be at least 6 chars long"
  }
}
```

Depending on how familiar you are with functional programming, you can approach this matter differently. The example above is quite fine, in my opinion, as it reduces the boilerplate by introducing a high-order function called `minLength`, that returns a validator function based on the number (expected length) you provide to it.

---

Also, pay attention that application rules are meant to be applied application-wide. This is the key point to reducing the boilerplate. Let's say you have a `phoneNumber` field which length must always be 8. You don't need to provide a validation rule to *each* instance of that field, that's crazy. Instead, define a single validation rule in the schema and provide that schema using `<FormProvider`>:

```jsx
// validation rules schema can be modularized into a separate file
const rules = {
  type: {
    tel: {
      minLength: minLength(8) // using the "minLength" high-order function from above
    }
  }
}

const App = () => (
  <FormProvider rules={rules}>
    <RootOfYouApp />
  </FormProvider>
)

ReactDOM.render(<App />, ...)
```

**Comment by kettanaito** [comment]
This was a good question, and I realized although it's not directly related to RAF, it would be nice to have recipes page showcasing best practices on using the library.

You can find [Recipes > Reducing boilerplate](https://redd.gitbook.io/react-advanced-form/recepies/reducing-boilerplate) section published now. It, essentially, described what I've written above.

**Comment by T-Roth** [comment]
I started down the path of using HOFs to generate the correct minLengh, maxLength rules that I need, which solves half my problem.  I don't think there is anything missing in the documentation, its more that I'm wanted to use RAF in a way that wasn't intended.  It looks like I would still have to generate all the messages with the correct length in them, which is something I was trying to avoid for maintainablility.   

This might not be a big deal though, the more I think about it I'm going to have to find a way to auto generate the messages and rules from my serverside schema.  There could be thousands of rules and I don't want to have to maintain all of them.

**Comment by kettanaito** [comment]
@T-Roth Did you mean something like this:

```js
const rules = {
  name: {
    firstName: {
      minLength: ({ value, variables }) => {
        const minLength = 6
        variables.minLength = 6
        return value.length >= minLength
      }
    }
  }
}

const messages = {
  name: {
    firstName: {
      rule: {
        minLength: ({ variables }) => `Need to have at least ${variables.minLength} chars`
      }
    }
  }
}
```
?

**Comment by T-Roth** [comment]
Yes, something like that, but I would like to be able to create different levels of messages for the rule

    const messages = {
        general: {
            minLength: ({ variables }) => `Must be at least ${variables.minLength} chars`
        },
        name: {
            firstName: {
                rule: {
                    minLength: ({ variables }) => `First Name must be at least ${variables.minLength} chars`
                }
            }
        }
    }

Since I'm going to try and auto gen the rules and messages I'm not  sure how useful of a feature this would be.

**Comment by kettanaito** [comment]
I'm closing this issue for now.

## Small recap:

* Use [High order validator functions](https://redd.gitbook.io/react-advanced-form/recepies/reducing-boilerplate#high-order-validator-functions) to reduce boilerplate when creating validation rules,
* Prefer declaring higher scope variables, if necessary, to reuse in the validation rules/messages, rather than expecting them from the schema context
