### ISSUE TITLE
Feature: Support initial values for form

### ISSUE THREAD

**Issue by Filson14** [kettanaito/react-advanced-form#262]
## Environment
* **OS:** Ubuntu 16.04
* **Node:** 10.4.1
* **NPM:** 6.1.0
* **react-advanaced-form:** 1.3.2

## What
RAF should provide feature to enable setting initial data for whole form (not just for field).

## Why
It is a common use case to use forms for data instance management / editing already existing data.

## How
How to reproduce the issue? / How do you see the implementation of the feature?
I would like to propose a new prop "initialData" (to be consistent with field initialData), where developer can provide object for the form with matching values. After some changes to form, the reset function should bring the initial data back.

## Keynotes
It's a common scenario to get some data from server and then fulfill a form with it to let user put some changes.

**Comment by kettanaito** [comment]
Thank you for submitting the feature request, @Filson14.
This is a good suggestion, and I think we should bring it in the upcoming releases.

We still need to think more about the spec, but at the moment I would suggest the following:

## API
```jsx
const initialValues = {
  [fieldPath]: initialValue,
  firstName: 'foo',
  lastName: 'bar',
  billingData: {
    address: 'Baker st.'
  },
}

<Form initialValues={initialValues}>
  <Input name="firstName" /> // "foo"
  <Input name="lastName" initialValue="custom" /> // "custom"
  <Field.Group name="billingData">
    <Input name="address" /> // "Baker st."
  </Field.Group>
</Form>
```

## General statements

1. Initial values is an object of the `{ [fieldPath: string]: value }` shape that is provided as a value to `initialValues` prop of the `Form` component.
1. Initial values object applies the values via deep merge into the `fields` Map of the Form, that implies that field groups must be provided explicitly.
1. When field component has its own `initialValue` prop specified, it takes the higher priority over the initial value from the `initialValues` prop of the form.

## Open questions

- [ ] Does `initialValues` implies that the fields are uncontrolled? Put differently: how to provide initial values an state that the fields must be controlled? Having alternate `Form.props.values`?

---

Right now I am working on the #250 pull request, which introduces major changes to the internals of the library. I wouldn't recommend to start any feature unless those changes are merged into master branch, to prevent merge conflicts.

**Comment by Filson14** [comment]
Not sure if I understand correctly the Open Question. I'm pretty new in react so it could be lack of knowledge. How form's initialValues could make fields be uncontrolled? It may just be the mechanism to set first value and the later synchronisation could be handled as is now. Although I have not dive deep into the source code, so it's just a consideration.

**Comment by kettanaito** [comment]
@Filson14 What I meant is that `initialValue` prop on inputs in React implies the input is [uncontrolled](https://reactjs.org/docs/uncontrolled-components.html). `value`, on the other hand, means that the input is [controlled](https://reactjs.org/docs/forms.html#controlled-components).

That is why I'm cautious regarding the expectations how the prop is intended to work. Probably, it's safe to start from `initialValues` and uncontrolled inputs. Making an input controlled is an explicit behavior, thus I wouldn't assume it by introducing something like `values` prop on the form.

**Comment by kettanaito** [comment]
This feature will be included in the next minor release `1.5.0`. Looking forward to see it running.

**Comment by kettanaito** [comment]
[`1.5.0`](https://github.com/kettanaito/react-advanced-form/releases/tag/1.5.0) has been published! Update and use this, and a few other new features. Refer to the documentation on the API and usage examples.

**Comment by kettanaito** [comment]
@Filson14 I would be very thankful if you had some time to test this functionality, as well as the newest release. Please let me know if anything. Thanks.

**Comment by Filson14** [comment]
For sure! Unfortunately I won't be able to do this right now, sorry (higher priorities :wink:).

**Comment by h0wXD** [comment]
Hi, I have been using the initial values and it works great. Is there any way to re-initialize the form with newer initial values? e.g. I navigated to the form page, having a loading screen with ongoing fetch. Form gets rendered with outdated values (passed down from store). Store gets updated, component re-rendered, new initialValues come down, but nothing happens. I also tried triggering form reset after new initialValues come down. Seems they are really initial. I could change my approach to only navigate to the form after loading the data to get around this. Did I miss something? Thanks for the great library! Loving it so far!

**Comment by kettanaito** [comment]
Hi, @h0wXD. Thanks for the feedback.

What you have described is a controlled input pattern. That is not designed to be solved with update of initial values. Although it is tempting, do not try to force controlled behavior for `initialValues`, this violates how data flows in your form.

Instead, you can make all fields controlled, while each value for a field is stored in Redux store, for example.

```jsx
import React from 'react'
import { connect } from 'react-redux'
import { Form } from 'react-advanced-form'
import { Input, Checkbox } from './your-fields'
import { updateFieldValue } from './reducer/actions'

class MyExample extends React.Component {
  handleFieldChange = ({ nextValue, fieldProps }) => {
    this.props.updateFieldValue({ [fieldProps.name]: nextValue })
  }

  render() {
    const { values } = this.props // field values bind via Redux connector
  
    return (
      <Form>
        <Input name="username" value={values.username} onChange={this.handleFieldChange} />
        <Checkbox name="foo" checked={values.foo} onChange={this.handleFieldChange} />
      </Form>
    )
  }
}

export default connect(state => ({
  values: state.values,
}), { updateFieldValue })(MyExample)
```

Making fields values controlled also means you need to handle their updates (see `this.handleFieldChange` method). You can still use `initialValue`/`initialValues` with controlled fields.

Hope this helps.

**Comment by h0wXD** [comment]
Hi @kettanaito thanks for the quick update and code example. 

You are right with the controlled behavior. Somehow I was expecting the form to reset entirely if a new instance of initialValues was passed down (a new 'initial' render, not really controlled behavior, because all form/validation state would be gone). Thanks for clarifying. 

I like react-advanced-forms because for it's simplicity and not having to manage the form data / state. The solution I went with is not rendering the form before initialValues being loaded, and show a loading screen. With this is approach everything is working as expected. Thanks!

**Comment by kettanaito** [comment]
@h0wXD I am glad you have manage it!
