### ISSUE TITLE
Force "required" prop on a field depending on its form's rules

### ISSUE THREAD

**Issue by T-Roth** [kettanaito/react-advanced-form#263]
## What
Allow "required" to be set in a rule's definition instead of form attribute

## Why
I'm auto generating my validation rules and would like to keep the validation defined in one place.  Having to maintain the "required" attribute on inputs could get out of sync and require extra maintenance.

## How
```
authorizationKey: {
            length: validation.isLengthBetween(8,14),
            oneNumber: validation.hasOneNumber,
            required: true <---
}
```
## Keynotes
It would also be nice if it could maintain the same behavior as the attribute where the other rules for a field are not evaluated if the required rule is not met.

**Comment by T-Roth** [comment]
enforceProps might work, but how do I get to the validation schema?   I'll need a way to access the schema that the Form is using that the current input is a part of.  I plan on generating a validation schema per model and could have hundreds of forms in my app.

**Comment by T-Roth** [comment]
I also tried forcing the required property to be true, and its not working, no required validation is being triggered in the UI.

```
const enforceProps = (ref:any) => {
    const props = fieldPresets.input.enforceProps(ref);
    props.required = true;  <---make everything required
    return props;
}

const getFieldPresets = () => {
    const props = Object.assign({}, fieldPresets.input, {enforceProps});
    return props;
}

export default createField(getFieldPresets())(Input);
```

**Comment by kettanaito** [comment]
I've experimented with your use case, and I think `mapPropsToField` is the correct option to use.

Here's an example for you where field class can force a `required` prop on a field depending on its parent `form.props.rules` (access to the validation schema passed to the parent form component) — https://codesandbox.io/s/yw97npxrwx?module=%2Fsrc%2Ffields%2FInput.js

Let me know if that answers your question.

**Comment by kettanaito** [comment]
I'm closing this issue, as it requires no additional work to be done on the library.

Please see my response above and let me know in this thread if everything is clear. Thank you once more for reaching out!

**Comment by T-Roth** [comment]
Sorry I didn't get back to you sooner, your suggestion is working.
Thanks for the help.


This is what I quickly came up with in case someone else wants to go this route:

```
const isRequiredValue = (value: ()=>boolean) : boolean => {
    const isFunction = typeof(value) === "function"
    if(isFunction) {
        return value() === true;
    } 
    return false;
}

const getRequiredValue = (fieldRules: any) : boolean => {
    if(fieldRules !== undefined 
        && typeof(fieldRules.get) === "function"
        && fieldRules.get("required") !== undefined) {

        return isRequiredValue(fieldRules.get("required"))
    }
    return false;
}

const requiredThroughName = (formRules: any, fieldName: string) => {
    const nameRules = formRules.get("name");
    
    return getRequiredValue(nameRules.get(fieldName));
}

const requiredThroughType = (formRules: any, fieldType: string) => {
    const typeRules = formRules.get("type");
    return getRequiredValue(typeRules.get(fieldType));
}

const shouldForceRequired = (context:any, field: any) => {
    const formRules = context.form.formRules;
    
    const isRequired = (
         requiredThroughName(formRules, field.name)
        || requiredThroughType(formRules, field.type)
    );

    return isRequired
}
  
const fieldOptions = Object.assign({}, fieldPresets.input, {
    mapPropsToField: (args:any) => ({
        ...args.fieldRecord,
        required: shouldForceRequired(args.context, args.fieldRecord)
    })
})
  
export default createField(fieldOptions)(Input)
```

**Comment by kettanaito** [comment]
@T-Roth I'm glad I could help you.

If I may, there is a slightly lighter version of the same solution you've come up with:

```js
const getRequiredProp = (formRules) => {
  return (fieldSelector) => {
    const fieldRules = formRules.getIn(fieldSelector)

    if (fieldRules) {
      const required = fieldRules.get('required')
      return typeof required === 'function'
        ? required()
        : required
    }

    return false
  }
}

const shouldForceRequired = (fieldRecord, context) => {
  const { formRules } = context.form

  return [
    ['type', fieldRecord.type],
    ['name', fieldRecord.name],
  ].some(getRequiredProp(formRules))
}

export default createField({
  ...fieldPresets.input,
  mapPropsToField: ({ fieldRecord, context }) => ({
    ...fieldRecord,
    required: shouldForceRequired(fieldRecord, context),
  })
})(Input)
```
