### ISSUE TITLE
Question: onSerialize prop or per custom field for version 1.4.1 

### ISSUE THREAD

**Issue by robertsonsamuel** [kettanaito/react-advanced-form#286]
## Environment
* **OS:** OS X 10.13.6
* **Node:** 10.6
* **NPM:** 6.10
* **react-advanaced-form:** 1.4.1

## What
What the issue or feature is about?

Was this released into 1.4.1? onSerialize per field prop or per custom field create, I can't seem to get to work.

## Why
Using this to transform moment.js dates for a datepicker to just plain date IE: `.format('YYYY/MM/DD')`, vs checking the field and transforming. 

## How
How to reproduce the issue? / How do you see the implementation of the feature?

Reproduced here:
https://codesandbox.io/s/6yny204z6k

## Keynotes
This might be in the 1.5 release but I didn't see this feature in pull request #274, or at least I couldn't tell based on that.

Thanks for the insight!  Love this library!!!

**Comment by kettanaito** [comment]
Hi, @robertsonsamuel.
First of all, thank you for the feedback! It means a lot to me hearing that people enjoy this library. This is the purpose I keep developing it.

As of `1.4.x`, transformation of serialized fields is not yet available. The feature has landed to the current `master` (https://github.com/kettanaito/react-advanced-form/pull/274/commits/4e4f3c32616bca5670ac0a339e7f34dd47b0a8d7#diff-4b724c380c516c7b1e5ce4b662bf333aR500) and will be available in the upcoming minor release `1.5.0`.

There is already a [documentation about `onSerialize`](https://redd.gitbook.io/react-advanced-form/components/form/callbacks/onserialize) prepared, where you can see its specification and usage examples.

Release of the next version should happen by the end of September. I am currently facing issues in Cypress tests where they fail to check a checkbox properly. Once I resolve everything the codebase will be ready.

**Comment by robertsonsamuel** [comment]
Fantastic! Understood, thank you for the quick reply @kettanaito, I really do love this library and think it has the correct approach to handling forms with React. Wonderful work and best of luck with `1.5.0`!!
