### ISSUE TITLE
Add style prop to the Form component

### ISSUE THREAD

**Issue by Martinnord** [kettanaito/react-advanced-form#292]
# What
Add a `style` prop to the `Form` component.

# Why
Since almost every elements has a `style` prop it would be awesome to see one here as well. It will open up more possibilities when styling your form and maybe speed up UI prototyping.

# How

TBA ;-)

**Comment by kettanaito** [comment]
Thanks for pointing this out, @Martinnord.

I would extend the proposal of this issue to **ensure props propagation to the `<form>` component**. This could be handled by spreading the custom props before attaching the RAF-specific ones.

I will try to cover this and publish under the next patch release.

**Comment by kettanaito** [comment]
After a short look it became evident why this wasn't implemented as spreading at the very beginning. If we spread all the props from `Form` onto `<form>` component, we would propagate our custom props to a common DOM element (props like `initialValues`, `onReset`, etc.). This results into error of unknown props, and thus isn't a safe option.

**Comment by kettanaito** [comment]
I have added the support for `style` prop on the `Form` component.

However, I have stumbled upon the current CI pipeline not working properly, producing falsy negative results. There will be no new release until #287 is fixed. Thank you for understanding.
