### ISSUE TITLE
How to use for File Inputs?

### ISSUE THREAD

**Issue by robertsonsamuel** [kettanaito/react-advanced-form#297]
# What

This might be possible already, however playing with this myself I've gotten no luck.
Looking to see if there could be a way to pass around an input with `type="file"`. I've use the `createField` with input presets to try this and have gotten close, however keeping the value is the issue. 

# Why
File uploads are useful, giving feedback with errors on this, of course with async validation requests would be great!

# How
It seems the event isn't propagating when the field is controlled, or if I create a custom handler for this on the created field. 

`FileInput.jsx`
```jsx
handleChange = event => {
    this.props.handleFieldChange({event: event, nextValue: event.target.files[0] })
}

// ....

<input {...fieldProps} type="file" onChange={this.handleChange} />


export default createField({
  valuePropName: 'value'
})(FileInput);

```

This then comes back with just the file name, which works, however to actually upload that file the value is incorrect, as we need the whole file blob. 

Creating a custom onChange method for the `input` works up until you try and set the value on the `<FileInput value={this.state.file}/>` as you get back an error saying you can't place a string on that type of element.
 

Any insight for a way to handle file inputs? I'm aiming to catch any errors with the file via js, using react-advanced-form, then allow a direct upload. 

If not I'll stick to writing that validation, but if this library can do that for me at some point that would be awesome!

Thanks again!

**Comment by kettanaito** [comment]
Hello, @robertsonsamuel.
Thanks for a question.

I've put an example of the basic implementation of `FileInput`: https://github.com/kettanaito/react-advanced-form/blob/master/examples/fields/FileInput.jsx. I've tested it on both controlled and uncontrolled scenarios and it worked properly. Unfortunately, there is no way to test file inputs in Cypress, so I cannot add it to the integration suit cases at the moment.

A few comments regarding your excerpts:
* No need to use `valuePropName: 'value'`, as this is the default value for `valuePropName`.
* No need to propagate `event` to the `this.handleFieldChange` callback method exposed by `createField`. You can, of course, but this is not mandatory.

Please, let me know what caused a confusion during the implementation.

**Comment by robertsonsamuel** [comment]
Thanks so much for that example and the quick response as always!
I think my main confusion came from the `enforceProps` property. That file example is the best explanation in itself of how useful that property is! This solves my issue, fantastic work as always 🎉

**Comment by kettanaito** [comment]
I find certain parts of `createField` API somewhat confusing. There is already changes planned for the next major version to adjust the API and make it more straightforward.

Glad your question was answered. Your feedback is always welcomed!
