### ISSUE TITLE
Make "value" a possibly dynamic prop

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#33]
## What
Need to allow to make `Field.props.value` a dynamic prop (dependant from the form's state).

## Why
There's a usecase you would like to have a certain field pre-filled once another field has a certain value:
```jsx
<Field.Input value={({ fields }) => {
  return fields.anotherField && (fields.anotherField.value === 'foo') && 'Pre-filled value';
}} />
```

**Comment by kettanaito** [comment]
This really relates to the`initialValue`. Still under discussion.

**Comment by Vidlec** [comment]
I am in favor of dropping this. 
If somebody need this feature he can easily achieve it by making the filed controllable and handling the logic in onChange function

**Comment by kettanaito** [comment]
@Vidlec I agree with you. I would close this unless there is a real scenario for this.

Closing.
