### ISSUE TITLE
Custom Select Field Not Updating

### ISSUE THREAD

**Issue by jerrywithaz** [kettanaito/react-advanced-form#368]
# What
I am trying to build a simple custom select element that uses a controlled input field to store the value.

## Current behavior
The field state is not updated when this.props.handleFieldChange({nextValue: selectedIndex}) is called and the value never changes past the initial value.

## Expected behavior
I should be able to call this.props.handleFieldChange({nextValue: selectedIndex}); and it should update the fieldState.

# How

## My Custom Form Select Element

```
<Form.Select name="ViewType" ariaLabel="Filter by View Type" initialValue={initialValues.viewType} options={viewTypes} style={showSelect(viewTypes)}/>
```

## The Created Field Component Using RAF
```
class FormSelect extends React.Component {

    onChange = selectedIndex => {
        this.props.handleFieldChange({nextValue: selectedIndex});
    }

    render() {
        const {
            fieldProps,
            fieldState,
            children,
            handleFieldChange,
            handleFieldBlur,
            handleFieldFocus,
            initialValue,
            ...rest
        } = this.props;

        const {required} = fieldProps;

        const {touched, invalid, errors} = fieldState;

        const error = invalid && errors && errors.length
            ? errors[0]
            : null;

        return (
            <div className="ezform__field">
                <Select {...this.props} invalid={invalid} onChange={this.onChange}>
                    {children}
                </Select>
                {error && <FormError message={error} visible={invalid} theme="large"/>}
            </div>
        );
    }

}
```
## My Select Component (Render and Change Functions)

```
/**
     * Event handler fired when an item in the dropdown is clicked.
     * @param {UIEvent} e - item click event
     */
    onItemClicked = (e, selectedIndex) => {

        e.stopPropagation();

        e.preventDefault();

        this.setState({
            selectedIndex: selectedIndex
        }, () => {

            this.triggerBlur();

            this.triggerChange();

        });

    }

    triggerChange = e => {

        const {selectedIndex} = this.state;

        this.props.onChange(selectedIndex);

    }

render() {

        const {focused, dropdownExpanded, selectedIndex, options} = this.state;

        const {
            id,
            name,
            ariaLabel,
            theme,
            disabled,
            autoFocus,
            required,
            invalid,
            style,
            className,
            fieldProps,
            fieldState
        } = this.props;

        //Class configuration for the root element
        const elementClassConfig = {
            "ezselect": true,
            "ezselect--disabled": disabled
        };

        const elementClassName = classNames(elementClassConfig) + className;

        //Class configuration for the custom dropdown element
        const listClassConfig = {
            "ezselect__list": true,
            "ezselect__list--visible": focused
        };

        const listClassName = classNames(listClassConfig);

        const value = options[selectedIndex].value;

        //Either use the fieldProps prop from React Advanced forms or map the properties to a new object
        const properties = fieldProps ? fieldProps : {
            "name": name,
            "disabled": disabled,
            "required": required,
            "onChange": () => {}
        };

        return (
            <div id={`ezselect-${id}`} className={elementClassName} style={style}>
                <div className="ezselect__element" ref={this.element} tabIndex={0} autoFocus={autoFocus} onFocus={this.onElementFocus} onBlur={this.onElementBlur}>
                    <div className="ezselect__root" onClick={this.onRootClick}>
                        <span className="ezselect__name">{this.renderRootItemText(selectedIndex, options)}</span>
                        <span className="ezselect__icon ion-android-arrow-dropdown"></span>
                    </div>
                    <ul className={listClassName}>{this.renderOptions(selectedIndex, options)}</ul>
                </div>
                <input {...properties} id={id || name} value={value} aria-label={ariaLabel} aria-invalid={invalid}/>
            </div>
        );
    }

```

**Comment by kettanaito** [comment]
Hi, @jerrywithaz. Thanks reaching out.

I've put up a similar scenario on the [Codesandbox](https://codesandbox.io/s/l2qxw1vkjm). Please see and let me know if this is what you are trying to achieve. Of course, you may want to play around with your `CustomSelect` component to affect the rendering of the options list depending on the field's state.

From what I see our implementations are very similar. The only place where the difference may occur is *what* and *where* you wrap in the `createField` high-order component. Please pay attention to that in the sandbox I've posted.

**Comment by jerrywithaz** [comment]
Hi, @kettanaito 

Thanks so much for the Sandbox that really helped me narrow it down some but I still can't get it to work quite right.

So, I took the liberty of putting my custom select in the [Sandbox ](https://codesandbox.io/s/rm779o8mjn) so that you can see what I am doing, mine has a little more functionality in that its an actual dropdown that expands and collapses but nothing too fancy.

I am console logging the "nextValue" for both of our "FormSelect" component and as you can see the correct next value is passed to the handleFieldChange function.

And, in my Select component the value never seems to update and I cannot figure out why.

I am also console logging the serialized form and my select components value never seems to stick.

Any ideas?

**Comment by kettanaito** [comment]
I will take a look once I have a spare minute. Follow this issue for updates. Thanks.

**Comment by kettanaito** [comment]
Getting back to the scenario, I have updated your sandbox to include proper handlers invocation (https://codesandbox.io/s/538olnyzq4). To sum it up:

* No need to call `this.props.onChange` in a custom handler where you already call `this.props.handleFieldChange()`. The latter method always invokes custom `onChange`, whenever present.
* Generally, the communication between the fields was good, I haven't touched it.

As you can see in the logs, the value change and the serialization works as needed. **However**, I've discovered an issue caused by the field blur handler. Whenever a blur handler is invoked, and its updates are reflected in the form's state, it tries to diff the values and conditionally perform the `onChange` dispatch:

https://github.com/kettanaito/react-advanced-form/blob/288fe08ca357f170534fd16606b73defc414e5c9/src/components/Form.jsx#L374-L388

For some reason the `value` of a field carried within the blue handler is an empty string (possibly obsolete value), the equality check makes that condition pass, resulting into *another* invocation of `onChange` handler, where `nextValue: ''`. This erazes the proper value in the state.

This logic is wrong, and I have already re-written it as a part of #354. Dispatch of a custom `onChange` will no longer be in the generic update handler, but will always be derived from the respective field change event.

**Comment by jerrywithaz** [comment]
Thanks so much for the update! I was actually working on it this morning and realized the blur trigger was the issue but now I understand exactly why it is this case.

It is no longer an issue for me as I realized that before I change the state of my Select Component I need to call `handleFieldChange` and then set the state and then trigger the blur.

As such:

```
onItemClicked = (e, selectedIndex) => {

    e.stopPropagation();

    e.preventDefault();

    this.triggerChange(selectedIndex);

    this.setState({
        selectedIndex: selectedIndex
    }, () => {
        this.triggerBlur();
    });
}

```

For whatever reason, triggering the change after calling setState caused the handleFieldChange to run twice and the field would never update.

I am actually not sure if this is the same issue you're referring to above but thanks again!

**Comment by kettanaito** [comment]
Happy to hear that, @jerrywithaz!

Yes, it's what I'm referring to. Feel free to ask any questions you have, and let your forms be great.
