### ISSUE TITLE
bundlesize dependency

### ISSUE THREAD

**Issue by vbulant** [kettanaito/react-advanced-form#383]
# Environment
All

# What
Since `bundlesize` dependency is being used just for a test command in circleci, I believe it should be included as a devDependency.

## Current behavior
`bundlesize` is included as dependency

## Expected behavior
`bundlesize` is included as devDependency

# Why
`bundlesize` is not needed for a regular usage of the library

# How
Add `react-advanced-form` as a dependency to any project, then run `npm install`. `bundlesize` is installed even though it’s not used by `react-advanced-form`.

**Comment by kettanaito** [comment]
Thanks for reporting the issue, @vbulant.

It looks like dependency misconfiguration. I will fix it and merge it today.

**Comment by kettanaito** [comment]
Fixed and published under [`1.7.1`](https://github.com/kettanaito/react-advanced-form/tree/ab8114848253233f93a2dbdf764b73c66fa9d34a). Please install the latest version and let me know that the issue is fixed.

**Comment by vbulant** [comment]
@kettanaito Tested, issue is gone. Thank you for the swift action 🙂
