### ISSUE TITLE
Adopt strong types (TypeScript)

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#4]
## What
Need to make the library strongly typed. TypeScript if preferable.

## Why
Strong types guarantee seamless types usages, eradicate bugs and help during the development.

**Comment by kettanaito** [comment]
While this is certainly a must, there is not enough time to implement this for version 1.0. Postponing.

**Comment by kettanaito** [comment]
I will postpone this issue until we meet `1.0`. There is a chance we will not adopt TypeScript at all.

Closing.

**Comment by aidankmcl** [comment]
Hi! I really like how this library approaches forms and would like to use it in my app, however we use TypeScript. Any plans to include an `index.d.ts` so it can play well with TS projects? I will give it a shot today but unfortunately cannot invest too much time at the moment.

**Comment by kettanaito** [comment]
Hey, @aidankmcl. Thanks for the feedback!

Definitely, it would be great to include a type definition file, and this is something I have on my todo list. I can't promise any exact dates, since there are some features I would like to rollout as a top priority.

One thing I can suggest is to introduce type definitions gradually. I can't estimate how long it would take to ship a single `index.d.ts` with everything perfectly typed, but I think it should be possible to release at least some basic definitions and continuously update them. What would you say?

Any help is welcome as well. I don't have a ton of experience with TypeScript, so I would be happy to have somebody to review my code.

**Comment by kettanaito** [comment]
Also, I would like to implement #272 prior to touching in-depth types.

From my experience it is somewhat frustrating to type annotate ImmutableJS, so I would like to remove it from the library's internals first, to prevent time spent on annotating something that would be removed in the future anyway.

**Comment by aidankmcl** [comment]
Hey @kettanaito, I would happily take a look! I am a beginner in TypeScript myself but can lend an extra pair of eyes if you like.

**Comment by kettanaito** [comment]
That would be great!

I have just got to the point of finilazing a huge chunk of changes, and there has been a few features which are really essential to have. There is enough work planned for my free time for the next 2-3 weeks. Regardless, I will try to at least start with typings, and will assign you as a pull request reviewer just in case :)

**Comment by aidankmcl** [comment]
Thank you very much for all your work! I'll be on the lookout :)

**Comment by kettanaito** [comment]
I've created a separate issue dedicated to our topic #273. We can do potential discussion during the introduction of those types there. Thanks.
