### ISSUE TITLE
Introduce "Field.props.initialValue"

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/react-advanced-form#45]
## What
Need to have an ability to pre-fill the field without making it fully controllable on the end-side.

## Why
Right now passing `Field.props.value` will indeed pre-fill the field, but then you ought to control its value by yourself. This is not always a desired behavior.

## How
1. Introduce new `initialValue` prop on Field
2. Make it propagate properly through optional `connectField` (just pass through)
3. Set the `value` in the `Field.componentWillMount` based on `initialValue`

**Comment by kettanaito** [comment]
Are you planning to do this change @Vidlec?

**Comment by Vidlec** [comment]
Yes!

**Comment by Vidlec** [comment]
Addressed in #49 [Added initial value]

**Comment by kettanaito** [comment]
@Vidlec approved. Feel free to merge and close the issue.
